{
 "title": "でかプ実績",
 "description": "でかプの統計情報を表示します",
 "tags": [
  "VRChat",
  "でかプ"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "ユーザー名",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\n\r\nschema.tagValues(\r\n  bucket: \"dekapu-log\",\r\n  tag: \"user\"\r\n)"
    }
   }
  ]
 },
 "panels": [
  { "title": "統計", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "総獲得",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "総獲得推移",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)\r\n"
    }
   ]
  },
  {
   "title": "獲得速度(枚/min)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all_delta_1m\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\n  |> filter(fn: (r) => r._field == \"credit_all_delta_1m\")\n  |> filter(fn: (r) => r.user == \"${user}\")\n  |> movingAverage(n: 60)\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "本日の総獲得",
   "type": "stat",
   "description": "9時リセット",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\r\noption location = timezone.location(name: \"Asia/Tokyo\")\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: 9h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n  |> last()"
    }
   ]
  },
  {
   "title": "クレジット所持数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"credit\")\r\n  |> filter(fn: (r) => r[\"user\"] == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "1時間当たりの獲得数推移",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "獲得数ヒートマップ",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"credit_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      time: r._time,\r\n      value: r._value,\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "プレイ時間",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"playtime\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "最大獲得速度/min",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"math\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"cpm_max\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: float(v: math.floor(x: r._value))\r\n      }))\r\n"
    }
   ]
  },
  {
   "title": "ルーレット回転",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_start\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "フィーバー発生",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_getfev\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ルーレット当選",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_hit\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "フィーバー時回転",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"slot_startfev\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "シャルベ救出数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"buy_shbi\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "お部屋シャルベクリック数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"rmshbi_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "タスク完了数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"task_cnt\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "メダルタワー獲得数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"get_medaltower\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ボーナスステップ報酬回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"bstp_rwd\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "スキルポイント使用数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sp_use\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "実績獲得数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"l_achieve_count\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "黒箱獲得総数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"bbox_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "黒箱獲得率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"task_cnt\" or r._field == \"bbox_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.task_cnt and r.task_cnt != 0.0 \r\n              then float(v: r.bbox_all) / float(v: r.task_cnt) \r\n              else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "黒箱ショップ利用数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"bbox_shop\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  { "title": "JACKPOT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "S-JPスタート値最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_startmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "P-JPスタート値最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_startmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "F-JPスタート値最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_startmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "パレッタチャンス挑戦回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t1\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"2段目\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"3段目\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t3\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"最終段\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t4\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"秘密の段\" }))\r\n"
    }
   ]
  },
  {
   "title": "パレッタボール内部ストック",
   "type": "timeseries",
   "description": "この値が増えていく場合はクルーン抽選速度より速い速度でパレッタボールを獲得してしまっており、内部ストックがたまっている状況。\n\nなおY軸の値が内部ストック値ではない。ストックがあるままRejoinすると値がずれていくのでオフセットが乗っかる場合があることに留意すること。（値にとらわれず上下の変化を見ること）",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 23 },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> filter(fn: (r) => r._field == \"palball_get\" or r._field == \"pallot_lot_t0\")\r\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r.palball_get - r.pallot_lot_t0\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> yield(name: \"difference\")\r\n"
    }
   ]
  },
  {
   "title": "S-JP最終結果最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_totalmax_v2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "P-JP最終結果最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_totalmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "F-JP最終結果最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_totalmax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "パレッタJACKPOT種別",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"シングル\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t1\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ダブル\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"マッシブ\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t3\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ヘブン\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t4\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ギャラクシー\" }))"
    }
   ]
  },
  {
   "title": " S-JP獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "P-JP獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "F-JP獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "パレッタJACKPOT当選率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t0\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"シングル\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t0) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t1\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"ダブル\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t1) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t2\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"マッシブ\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t2) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t3\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"ヘブン\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t3) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_t4\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _measurement: \"ギャラクシー\",\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 then float(v: r.jacksp_get_t4) / float(v: r.pallot_lot_t0) else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "パレッタボール獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ゴールデンパレッタボール獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_palball_get_100\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ゴールデンボール率",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_palball_get_100\" or r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.pallot_lot_t0 and r.pallot_lot_t0 != 0.0 \r\n              then float(v: r.dc_palball_get_100) / float(v: r.pallot_lot_t0) \r\n              else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "フェレッタJACKPOT種別",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"シングル\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_t1\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ダブル\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_t2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"マッシブ\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_t3\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ヘブン\" }))"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jackfr_get_t4\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> drop(columns: [\"user\", \"_measurement\"])\r\n  |> map(fn: (r) => ({ r with _field: \"ユニバース\" }))"
    }
   ]
  },
  {
   "title": "PJP当選率(全体)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "jacksp = from(bucket: \"dekapu-log\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> rename(columns: {_value: \"jacksp_value\"})\r\n\r\npallot = from(bucket: \"dekapu-log\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"pallot_lot_t0\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> rename(columns: {_value: \"pallot_value\"})\r\n\r\njoin(tables: {jacksp: jacksp, pallot: pallot}, on: [\"user\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.pallot_value and r.pallot_value != 0.0\r\n              then float(v: r.jacksp_value) / float(v: r.pallot_value)\r\n              else 0.0,\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "フェレッタボール獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferball_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "フェレッタチャンス挑戦回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferlot_lot\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Fチャンス獲得ナンバー数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferlot_act\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Fチャンスアイテムポケット入賞",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferlot_chance\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Fチャンス獲得ライン数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferlot_lines\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ビンゴ最大同時ライン",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ferlot_maxln\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "1時間ごとのパレッタ当選率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "jacksp = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"jacksp_get_all\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({r with _field: \"PJP獲得数\"}))\r\n\r\npallot = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"pallot_lot_t0\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({r with _field: \"ボール獲得数\"}))\r\n\r\nratio = join(\r\n    tables: {jacksp: jacksp, pallot: pallot},\r\n    on: [\"_time\"]\r\n  )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: \"PJP当選率\",\r\n      _value: if exists r._value_pallot and r._value_pallot != 0.0\r\n              then float(v: r._value_jacksp) / float(v: r._value_pallot)\r\n              else 0.0\r\n  }))\r\n\r\nunion(tables: [jacksp, pallot, ratio])\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> yield(name: \"PJP当選率\")\r\n"
    }
   ]
  },
  {
   "title": "1時間当たりのS-JP獲得数",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> rename(columns: {_value: \"sqr_step\"})\r\n"
    }
   ]
  },
  {
   "title": "P-JP 獲得数",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jacksp_get_all\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  { "title": "すごろく", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "すごろく獲得回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Ultimate回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "1時間当たりの進行回数推移",
   "type": "barchart",
   "description": "数値が大きいほど遠心分離しゃる",
   "gridPos": { "h": 9, "w": 5, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "1時間当たりの平均周回数推移",
   "type": "barchart",
   "description": "小さいほどUMコンボを狙いやすい",
   "gridPos": { "h": 9, "w": 5, "x": 11, "y": 47 },
   "targets": [
    {
     "query": "sqr = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> rename(columns: {_value: \"sqr_step\"})\r\n\r\njack = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> rename(columns: {_value: \"jack_get\"})\r\n\r\njoin(tables: {sqr: sqr, jack: jack}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r.jack_get > 0.0 \r\n              then float(v: r.sqr_step) / (float(v: r.jack_get) * 16.0) \r\n              else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "すごろく",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
    },
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "すごろく進行回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "Ultimate最大コンボ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_combomax\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "すごろく平均周回数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"sqr_step\" or r._field == \"jack_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> pivot(\r\n      rowKey:[\"_time\"],\r\n      columnKey:[\"_field\"],\r\n      valueColumn:\"_value\"\r\n    )\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if exists r.jack_get and r.jack_get > 0.0 \r\n              then float(v: r.sqr_step) / (float(v: r.jack_get) * 16.0) \r\n              else 0.0\r\n    }))\r\n"
    }
   ]
  },
  {
   "title": "Ultimate最終結果最高",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ult_totalmax_v2\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  { "title": "トーテム", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "トーテム設置",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^l_totems_set_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"l_totems_set_1\" then \"祭壇1\"\r\n        else if r._field == \"l_totems_set_2\" then \"祭壇2\"\r\n        else if r._field == \"l_totems_set_3\" then \"祭壇3\"\r\n        else if r._field == \"l_totems_set_4\" then \"祭壇4\"\r\n        else if r._field == \"l_totems_set_5\" then \"祭壇5\"\r\n        else r._field,\r\n      _value:\r\n        if r._value == 0 then \"なし\"\r\n        else if r._value == 1 then \"橙\"\r\n        else if r._value == 2 then \"緑\"\r\n        else if r._value == 4 then \"ピンク\"\r\n        else if r._value == 5 then \"紫\"\r\n        else if r._value == 6 then \"白\"\r\n        else if r._value == 7 then \"水色\"\r\n        else if r._value == 8 then \"灰桜\"\r\n        else if r._value == 9 then \"群青\"\r\n        else if r._value == 10 then \"赤\"\r\n        else if r._value == 11 then \"クリーム\"\r\n        else if r._value == 12 then \"ミント\"\r\n        else if r._value == 13 then \"ピーチ\"\r\n        else if r._value == 14 then \"星空\"\r\n        else if r._value == 15 then \"草原\"\r\n        else if r._value == 16 then \"黒\"\r\n        else if r._value == 17 then \"黄\"\r\n        else if r._value == 18 then \"ラベンダー\"\r\n        else if r._value == 19 then \"ライム\"\r\n        else string(v: r._value)\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "トーテム設置履歴",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 57 },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^l_totems_set_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"l_totems_set_1\" then \"祭壇1\"\r\n        else if r._field == \"l_totems_set_2\" then \"祭壇2\"\r\n        else if r._field == \"l_totems_set_3\" then \"祭壇3\"\r\n        else if r._field == \"l_totems_set_4\" then \"祭壇4\"\r\n        else if r._field == \"l_totems_set_5\" then \"祭壇5\"\r\n        else r._field,\r\n      _value:\r\n        if r._value == 0 then \"なし\"\r\n        else if r._value == 1 then \"橙\"\r\n        else if r._value == 2 then \"緑\"\r\n        else if r._value == 4 then \"ピンク\"\r\n        else if r._value == 5 then \"紫\"\r\n        else if r._value == 6 then \"白\"\r\n        else if r._value == 7 then \"水色\"\r\n        else if r._value == 8 then \"灰桜\"\r\n        else if r._value == 9 then \"群青\"\r\n        else if r._value == 10 then \"赤\"\r\n        else if r._value == 11 then \"クリーム\"\r\n        else if r._value == 12 then \"ミント\"\r\n        else if r._value == 13 then \"ピーチ\"\r\n        else if r._value == 14 then \"星空\"\r\n        else if r._value == 15 then \"草原\"\r\n        else if r._value == 16 then \"黒\"\r\n        else if r._value == 17 then \"黄\"\r\n        else if r._value == 18 then \"ラベンダー\"\r\n        else if r._value == 19 then \"ライム\"\r\n        else string(v: r._value)\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  { "title": "ボール", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "ボール獲得数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ボール獲得数推移",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"ノーマル\"\r\n          else if r._field == \"dc_ball_get_1\" then \"橙\"\r\n          else if r._field == \"dc_ball_get_2\" then \"緑\"\r\n          else if r._field == \"dc_ball_get_3\" then \"レインボー\"\r\n          else if r._field == \"dc_ball_get_4\" then \"ピンク\"\r\n          else if r._field == \"dc_ball_get_5\" then \"紫\"\r\n          else if r._field == \"dc_ball_get_6\" then \"白\"\r\n          else if r._field == \"dc_ball_get_7\" then \"水色\"\r\n          else if r._field == \"dc_ball_get_8\" then \"灰桜\"\r\n          else if r._field == \"dc_ball_get_9\" then \"群青\"\r\n          else if r._field == \"dc_ball_get_10\" then \"赤\"\r\n          else if r._field == \"dc_ball_get_11\" then \"クリーム\"\r\n          else if r._field == \"dc_ball_get_12\" then \"ミント\"\r\n          else if r._field == \"dc_ball_get_13\" then \"ピーチ\"\r\n          else if r._field == \"dc_ball_get_14\" then \"星空\"\r\n          else if r._field == \"dc_ball_get_15\" then \"草原\"\r\n          else if r._field == \"dc_ball_get_16\" then \"黒\"\r\n          else if r._field == \"dc_ball_get_17\" then \"黄色\"\r\n          else if r._field == \"dc_ball_get_18\" then \"ラベンダー\"\r\n          else if r._field == \"dc_ball_get_19\" then \"ライム\"\r\n          else if r._field == \"dc_ball_get_20\" then \"若葉\"\r\n          else if r._field == \"dc_ball_get_70\" then \"参照エラー\"\r\n          else if r._field == \"dc_ball_get_71\" then \"デベロッパー\"\r\n          else if r._field == \"dc_ball_get_90\" then \"旧緑\"\r\n          else if r._field == \"dc_ball_get_91\" then \"橙（特殊）\"\r\n          else if r._field == \"dc_ball_get_100\" then \"ゴールデン\"\r\n          else if r._field == \"dc_ball_get_101\" then \"アメジスト\"\r\n          else if r._field == \"dc_ball_get_102\" then \"エメラルド\"\r\n          else if r._field == \"dc_ball_get_103\" then \"ローズクォーツ\"\r\n          else if r._field == \"dc_ball_get_104\" then \"トパーズ\"\r\n          else if r._field == \"dc_ball_get_105\" then \"サファイア\"\r\n          else if r._field == \"dc_ball_get_106\" then \"ダイヤモンド\"\r\n          else if r._field == \"dc_ball_get_334\" then \"抽選ボール\"\r\n          else if r._field == \"dc_ball_get_335\" then \"抽選（ボーナス）\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "ボール獲得構成比",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ndata = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"ノーマル\"\r\n          else if r._field == \"dc_ball_get_1\" then \"橙\"\r\n          else if r._field == \"dc_ball_get_2\" then \"緑\"\r\n          else if r._field == \"dc_ball_get_3\" then \"レインボー\"\r\n          else if r._field == \"dc_ball_get_4\" then \"ピンク\"\r\n          else if r._field == \"dc_ball_get_5\" then \"紫\"\r\n          else if r._field == \"dc_ball_get_6\" then \"白\"\r\n          else if r._field == \"dc_ball_get_7\" then \"水色\"\r\n          else if r._field == \"dc_ball_get_8\" then \"灰桜\"\r\n          else if r._field == \"dc_ball_get_9\" then \"群青\"\r\n          else if r._field == \"dc_ball_get_10\" then \"赤\"\r\n          else if r._field == \"dc_ball_get_11\" then \"クリーム\"\r\n          else if r._field == \"dc_ball_get_12\" then \"ミント\"\r\n          else if r._field == \"dc_ball_get_13\" then \"ピーチ\"\r\n          else if r._field == \"dc_ball_get_14\" then \"星空\"\r\n          else if r._field == \"dc_ball_get_15\" then \"草原\"\r\n          else if r._field == \"dc_ball_get_16\" then \"黒\"\r\n          else if r._field == \"dc_ball_get_17\" then \"黄色\"\r\n          else if r._field == \"dc_ball_get_18\" then \"ラベンダー\"\r\n          else if r._field == \"dc_ball_get_19\" then \"ライム\"\r\n          else if r._field == \"dc_ball_get_20\" then \"若葉\"\r\n          else if r._field == \"dc_ball_get_70\" then \"参照エラー\"\r\n          else if r._field == \"dc_ball_get_71\" then \"デベロッパー\"\r\n          else if r._field == \"dc_ball_get_90\" then \"旧緑\"\r\n          else if r._field == \"dc_ball_get_91\" then \"橙（特殊）\"\r\n          else if r._field == \"dc_ball_get_100\" then \"ゴールデン\"\r\n          else if r._field == \"dc_ball_get_101\" then \"アメジスト\"\r\n          else if r._field == \"dc_ball_get_102\" then \"エメラルド\"\r\n          else if r._field == \"dc_ball_get_103\" then \"ローズクォーツ\"\r\n          else if r._field == \"dc_ball_get_104\" then \"トパーズ\"\r\n          else if r._field == \"dc_ball_get_105\" then \"サファイア\"\r\n          else if r._field == \"dc_ball_get_106\" then \"ダイヤモンド\"\r\n          else if r._field == \"dc_ball_get_334\" then \"抽選ボール\"\r\n          else if r._field == \"dc_ball_get_335\" then \"抽選（ボーナス）\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\ntotals = data\r\n  |> group(columns: [\"_time\"])\r\n  |> sum(column: \"_value\")\r\n  |> rename(columns: {_value: \"total\"})\r\n\r\njoin(\r\n  tables: {d: data, t: totals},\r\n  on: [\"_time\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: r._field,\r\n      _value: float(v: r._value) / float(v: r.total) * 100.0\r\n  }))\r\n  |> group(columns: [\"_field\"])\r\n  \r\n"
    }
   ]
  },
  {
   "title": " 最大ボールナンバー",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_chain\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "ボール獲得数推移",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"ball_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  },
  {
   "title": "累計ボール獲得数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_get_0\" then \"ノーマル\"\r\n          else if r._field == \"dc_ball_get_1\" then \"橙\"\r\n          else if r._field == \"dc_ball_get_2\" then \"緑\"\r\n          else if r._field == \"dc_ball_get_3\" then \"レインボー\"\r\n          else if r._field == \"dc_ball_get_4\" then \"ピンク\"\r\n          else if r._field == \"dc_ball_get_5\" then \"紫\"\r\n          else if r._field == \"dc_ball_get_6\" then \"白\"\r\n          else if r._field == \"dc_ball_get_7\" then \"水色\"\r\n          else if r._field == \"dc_ball_get_8\" then \"灰桜\"\r\n          else if r._field == \"dc_ball_get_9\" then \"群青\"\r\n          else if r._field == \"dc_ball_get_10\" then \"赤\"\r\n          else if r._field == \"dc_ball_get_11\" then \"クリーム\"\r\n          else if r._field == \"dc_ball_get_12\" then \"ミント\"\r\n          else if r._field == \"dc_ball_get_13\" then \"ピーチ\"\r\n          else if r._field == \"dc_ball_get_14\" then \"星空\"\r\n          else if r._field == \"dc_ball_get_15\" then \"草原\"\r\n          else if r._field == \"dc_ball_get_16\" then \"黒\"\r\n          else if r._field == \"dc_ball_get_17\" then \"黄色\"\r\n          else if r._field == \"dc_ball_get_18\" then \"ラベンダー\"\r\n          else if r._field == \"dc_ball_get_19\" then \"ライム\"\r\n          else if r._field == \"dc_ball_get_20\" then \"若葉\"\r\n          else if r._field == \"dc_ball_get_70\" then \"参照エラー\"\r\n          else if r._field == \"dc_ball_get_71\" then \"デベロッパー\"\r\n          else if r._field == \"dc_ball_get_90\" then \"旧緑\"\r\n          else if r._field == \"dc_ball_get_91\" then \"橙（特殊）\"\r\n          else if r._field == \"dc_ball_get_100\" then \"ゴールデン\"\r\n          else if r._field == \"dc_ball_get_101\" then \"アメジスト\"\r\n          else if r._field == \"dc_ball_get_102\" then \"エメラルド\"\r\n          else if r._field == \"dc_ball_get_103\" then \"ローズクォーツ\"\r\n          else if r._field == \"dc_ball_get_104\" then \"トパーズ\"\r\n          else if r._field == \"dc_ball_get_105\" then \"サファイア\"\r\n          else if r._field == \"dc_ball_get_106\" then \"ダイヤモンド\"\r\n          else if r._field == \"dc_ball_get_334\" then \"抽選ボール\"\r\n          else if r._field == \"dc_ball_get_335\" then \"抽選（ボーナス）\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
    }
   ]
  },
  {
   "title": "ボール獲得割合前日比",
   "type": "stat",
   "description": "日本標準時で午前9時を基準にリセット",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"timezone\"\r\nimport \"strings\"\r\n\r\noption location = timezone.location(name: \"Asia/Tokyo\")\r\n\r\nball = from(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field == \"ball_get\" and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: 9h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n\r\nballs = from(bucket: \"dekapu-log\")\r\n  |> range(start: -2d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\" and r._field =~ /^dc_ball_get_/ and r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1d, offset: 9h, fn: last, createEmpty: false)\r\n  |> difference(nonNegative: true)\r\n\r\njoin(\r\n  tables: {balls: balls, ball: ball},\r\n  on: [\"_time\"],\r\n)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _value: if r._value_ball == 0.0 then 0.0 else float(v: r._value_balls) / float(v: r._value_ball) * 100.0\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field_balls\", \"_value\"])\r\n  |> difference(nonNegative: false, columns: [\"_value\"])\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field_balls:\r\n          if r._field_balls == \"dc_ball_get_0\" then \"ノーマル\"\r\n          else if r._field_balls == \"dc_ball_get_1\" then \"橙\"\r\n          else if r._field_balls == \"dc_ball_get_2\" then \"緑\"\r\n          else if r._field_balls == \"dc_ball_get_3\" then \"レインボー\"\r\n          else if r._field_balls == \"dc_ball_get_4\" then \"ピンク\"\r\n          else if r._field_balls == \"dc_ball_get_5\" then \"紫\"\r\n          else if r._field_balls == \"dc_ball_get_6\" then \"白\"\r\n          else if r._field_balls == \"dc_ball_get_7\" then \"水色\"\r\n          else if r._field_balls == \"dc_ball_get_8\" then \"灰桜\"\r\n          else if r._field_balls == \"dc_ball_get_9\" then \"群青\"\r\n          else if r._field_balls == \"dc_ball_get_10\" then \"赤\"\r\n          else if r._field_balls == \"dc_ball_get_11\" then \"クリーム\"\r\n          else if r._field_balls == \"dc_ball_get_12\" then \"ミント\"\r\n          else if r._field_balls == \"dc_ball_get_13\" then \"ピーチ\"\r\n          else if r._field_balls == \"dc_ball_get_14\" then \"星空\"\r\n          else if r._field_balls == \"dc_ball_get_15\" then \"草原\"\r\n          else if r._field_balls == \"dc_ball_get_16\" then \"黒\"\r\n          else if r._field_balls == \"dc_ball_get_17\" then \"黄色\"\r\n          else if r._field_balls == \"dc_ball_get_18\" then \"ラベンダー\"\r\n          else if r._field_balls == \"dc_ball_get_19\" then \"ライム\"\r\n          else if r._field_balls == \"dc_ball_get_20\" then \"若葉\"\r\n          else if r._field_balls == \"dc_ball_get_70\" then \"参照エラー\"\r\n          else if r._field_balls == \"dc_ball_get_71\" then \"デベロッパー\"\r\n          else if r._field_balls == \"dc_ball_get_90\" then \"旧緑\"\r\n          else if r._field_balls == \"dc_ball_get_91\" then \"橙（特殊）\"\r\n          else if r._field_balls == \"dc_ball_get_100\" then \"ゴールデン\"\r\n          else if r._field_balls == \"dc_ball_get_101\" then \"アメジスト\"\r\n          else if r._field_balls == \"dc_ball_get_102\" then \"エメラルド\"\r\n          else if r._field_balls == \"dc_ball_get_103\" then \"ローズクォーツ\"\r\n          else if r._field_balls == \"dc_ball_get_104\" then \"トパーズ\"\r\n          else if r._field_balls == \"dc_ball_get_105\" then \"サファイア\"\r\n          else if r._field_balls == \"dc_ball_get_106\" then \"ダイヤモンド\"\r\n          else if r._field_balls == \"dc_ball_get_334\" then \"抽選ボール\"\r\n          else if r._field_balls == \"dc_ball_get_335\" then \"抽選（ボーナス）\"\r\n          else strings.replace(v: r._field_balls, t: \"dc_ball_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n"
    }
   ]
  },
  {
   "title": "最大ボールチェイン数",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_ball_chain_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n          if r._field == \"dc_ball_chain_0\" then \"ノーマル\"\r\n          else if r._field == \"dc_ball_chain_1\" then \"橙\"\r\n          else if r._field == \"dc_ball_chain_2\" then \"緑\"\r\n          else if r._field == \"dc_ball_chain_3\" then \"レインボー\"\r\n          else if r._field == \"dc_ball_chain_4\" then \"ピンク\"\r\n          else if r._field == \"dc_ball_chain_5\" then \"紫\"\r\n          else if r._field == \"dc_ball_chain_6\" then \"白\"\r\n          else if r._field == \"dc_ball_chain_7\" then \"水色\"\r\n          else if r._field == \"dc_ball_chain_8\" then \"灰桜\"\r\n          else if r._field == \"dc_ball_chain_9\" then \"群青\"\r\n          else if r._field == \"dc_ball_chain_10\" then \"赤\"\r\n          else if r._field == \"dc_ball_chain_11\" then \"クリーム\"\r\n          else if r._field == \"dc_ball_chain_12\" then \"ミント\"\r\n          else if r._field == \"dc_ball_chain_13\" then \"ピーチ\"\r\n          else if r._field == \"dc_ball_chain_14\" then \"星空\"\r\n          else if r._field == \"dc_ball_chain_15\" then \"草原\"\r\n          else if r._field == \"dc_ball_chain_16\" then \"黒\"\r\n          else if r._field == \"dc_ball_chain_17\" then \"黄色\"\r\n          else if r._field == \"dc_ball_chain_18\" then \"ラベンダー\"\r\n          else if r._field == \"dc_ball_chain_19\" then \"ライム\"\r\n          else if r._field == \"dc_ball_chain_20\" then \"若葉\"\r\n          else if r._field == \"dc_ball_chain_70\" then \"参照エラー\"\r\n          else if r._field == \"dc_ball_chain_71\" then \"デベロッパー\"\r\n          else if r._field == \"dc_ball_chain_90\" then \"旧緑\"\r\n          else if r._field == \"dc_ball_chain_91\" then \"橙（特殊）\"\r\n          else if r._field == \"dc_ball_chain_100\" then \"ゴールデン\"\r\n          else if r._field == \"dc_ball_chain_101\" then \"アメジスト\"\r\n          else if r._field == \"dc_ball_chain_102\" then \"エメラルド\"\r\n          else if r._field == \"dc_ball_chain_103\" then \"ローズクォーツ\"\r\n          else if r._field == \"dc_ball_chain_104\" then \"トパーズ\"\r\n          else if r._field == \"dc_ball_chain_105\" then \"サファイア\"\r\n          else if r._field == \"dc_ball_chain_106\" then \"ダイヤモンド\"\r\n          else if r._field == \"dc_ball_chain_334\" then \"抽選ボール\"\r\n          else if r._field == \"dc_ball_chain_335\" then \"抽選（ボーナス）\"\r\n          else strings.replace(v: r._field, t: \"dc_ball_chain_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])\r\n"
    }
   ]
  },
  { "title": "メダル", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 } },
  {
   "title": "メダル獲得数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_get\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "メダル獲得数推移",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 4, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n        if r._field == \"dc_medal_get_0\" then \"ノーマル\"\r\n        else if r._field == \"dc_medal_get_1\" then \"ルーレット\"\r\n        else if r._field == \"dc_medal_get_2\" then \"緑\"\r\n        else if r._field == \"dc_medal_get_3\" then \"ピンク\"\r\n        else if r._field == \"dc_medal_get_4\" then \"紫\"\r\n        else if r._field == \"dc_medal_get_5\" then \"水色\"\r\n        else if r._field == \"dc_medal_get_6\" then \"ウォール\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP\"\r\n        else if r._field == \"dc_medal_get_12\" then \"圧縮緑\"\r\n        else if r._field == \"dc_medal_get_13\" then \"圧縮ピンク\"\r\n        else if r._field == \"dc_medal_get_14\" then \"圧縮紫\"\r\n        else if r._field == \"dc_medal_get_15\" then \"金\"\r\n        else if r._field == \"dc_medal_get_16\" then \"短い棒金\"\r\n        else if r._field == \"dc_medal_get_17\" then \"長い棒金\"\r\n        else if r._field == \"dc_medal_get_18\" then \"でかい金\"\r\n        else if r._field == \"dc_medal_get_19\" then \"とても大きい金\"\r\n        else if r._field == \"dc_medal_get_20\" then \"さらに大きい金\"\r\n        else if r._field == \"dc_medal_get_21\" then \"巨大金\"\r\n        else if r._field == \"dc_medal_get_22\" then \"超巨大金\"\r\n        else if r._field == \"dc_medal_get_100\" then \"レインボー\"\r\n        else if r._field == \"dc_medal_get_102\" then \"サファイア\"\r\n        else if r._field == \"dc_medal_get_103\" then \"ルビー\"\r\n        else if r._field == \"dc_medal_get_104\" then \"エメラルド\"\r\n        else if r._field == \"dc_medal_get_105\" then \"ダイヤモンド\"\r\n        else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])"
    }
   ]
  },
  {
   "title": "メダル獲得構成比",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\ndata = from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: false, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"dc_medal_get_0\" then \"ノーマル\"\r\n        else if r._field == \"dc_medal_get_1\" then \"ルーレット\"\r\n        else if r._field == \"dc_medal_get_2\" then \"緑\"\r\n        else if r._field == \"dc_medal_get_3\" then \"ピンク\"\r\n        else if r._field == \"dc_medal_get_4\" then \"紫\"\r\n        else if r._field == \"dc_medal_get_5\" then \"水色\"\r\n        else if r._field == \"dc_medal_get_6\" then \"ウォール\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP\"\r\n        else if r._field == \"dc_medal_get_12\" then \"圧縮緑\"\r\n        else if r._field == \"dc_medal_get_13\" then \"圧縮ピンク\"\r\n        else if r._field == \"dc_medal_get_14\" then \"圧縮紫\"\r\n        else if r._field == \"dc_medal_get_15\" then \"金\"\r\n        else if r._field == \"dc_medal_get_16\" then \"短い棒金\"\r\n        else if r._field == \"dc_medal_get_17\" then \"長い棒金\"\r\n        else if r._field == \"dc_medal_get_18\" then \"でかい金\"\r\n        else if r._field == \"dc_medal_get_19\" then \"とても大きい金\"\r\n        else if r._field == \"dc_medal_get_20\" then \"さらに大きい金\"\r\n        else if r._field == \"dc_medal_get_21\" then \"巨大金\"\r\n        else if r._field == \"dc_medal_get_22\" then \"超巨大金\"\r\n        else if r._field == \"dc_medal_get_100\" then \"レインボー\"\r\n        else if r._field == \"dc_medal_get_102\" then \"サファイア\"\r\n        else if r._field == \"dc_medal_get_103\" then \"ルビー\"\r\n        else if r._field == \"dc_medal_get_104\" then \"エメラルド\"\r\n        else if r._field == \"dc_medal_get_105\" then \"ダイヤモンド\"\r\n        else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n  }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n\r\ntotals = data\r\n  |> group(columns: [\"_time\"])\r\n  |> sum(column: \"_value\")\r\n  |> rename(columns: {_value: \"total\"})\r\n\r\njoin(\r\n  tables: {d: data, t: totals},\r\n  on: [\"_time\"]\r\n)\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _field: r._field,\r\n      _value: float(v: r._value) / float(v: r.total) * 100.0\r\n  }))\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "メダル投入数",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n"
    }
   ]
  },
  {
   "title": "1時間当たりの投入数推移",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: 1h, fn: last, createEmpty: true, timeSrc: \"_start\")\r\n  |> difference(nonNegative: true)\r\n  |> fill(column: \"_value\", value: 0)\r\n"
    }
   ]
  },
  {
   "title": "メダル投入数の推移",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"medal_in\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> derivative(unit: 1s, nonNegative: true)\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n"
    }
   ]
  },
  {
   "title": "累計メダル獲得数",
   "type": "stat",
   "gridPos": { "h": 9, "w": 13, "x": 11, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"strings\"\r\n\r\nfrom(bucket: \"dekapu-log\")\r\n  |> range(start: -1d)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field =~ /^dc_medal_get_/)\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n        r with\r\n        _field:\r\n        if r._field == \"dc_medal_get_0\" then \"ノーマル\"\r\n        else if r._field == \"dc_medal_get_1\" then \"ルーレット\"\r\n        else if r._field == \"dc_medal_get_2\" then \"緑\"\r\n        else if r._field == \"dc_medal_get_3\" then \"ピンク\"\r\n        else if r._field == \"dc_medal_get_4\" then \"紫\"\r\n        else if r._field == \"dc_medal_get_5\" then \"水色\"\r\n        else if r._field == \"dc_medal_get_6\" then \"ウォール\"\r\n        else if r._field == \"dc_medal_get_7\" then \"SP\"\r\n        else if r._field == \"dc_medal_get_12\" then \"圧縮緑\"\r\n        else if r._field == \"dc_medal_get_13\" then \"圧縮ピンク\"\r\n        else if r._field == \"dc_medal_get_14\" then \"圧縮紫\"\r\n        else if r._field == \"dc_medal_get_15\" then \"金\"\r\n        else if r._field == \"dc_medal_get_16\" then \"短い棒金\"\r\n        else if r._field == \"dc_medal_get_17\" then \"長い棒金\"\r\n        else if r._field == \"dc_medal_get_18\" then \"でかい金\"\r\n        else if r._field == \"dc_medal_get_19\" then \"とても大きい金\"\r\n        else if r._field == \"dc_medal_get_20\" then \"さらに大きい金\"\r\n        else if r._field == \"dc_medal_get_21\" then \"巨大金\"\r\n        else if r._field == \"dc_medal_get_22\" then \"超巨大金\"\r\n        else if r._field == \"dc_medal_get_100\" then \"レインボー\"\r\n        else if r._field == \"dc_medal_get_102\" then \"サファイア\"\r\n        else if r._field == \"dc_medal_get_103\" then \"ルビー\"\r\n        else if r._field == \"dc_medal_get_104\" then \"エメラルド\"\r\n        else if r._field == \"dc_medal_get_105\" then \"ダイヤモンド\"\r\n          else strings.replace(v: r._field, t: \"dc_medal_get_\", u: \"ID:\", i: 1)\r\n      }))\r\n  |> keep(columns: [\"_time\", \"_field\", \"_value\"])\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\"])"
    }
   ]
  },
  {
   "title": "スキルメダル獲得数",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "query": "from(bucket: \"dekapu-log\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"mpp-savedata\")\r\n  |> filter(fn: (r) => r._field == \"dc_medal_get_7\")\r\n  |> filter(fn: (r) => r.user == \"${user}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)\r\n  |> fill(column: \"_value\", usePrevious: true)"
    }
   ]
  }
 ]
}